### ISSUE TITLE
Needs to be able to support communication between master and client over Internet

### ISSUE THREAD

**Issue by jbregman** [Shadow-Soft/ansible-icinga2-client#1]
the master_fqdn has to be the ec2 internal DNS name because that's the name of the certificate on disk, BUT the same ansible variable master_fqdn is used for the Icinga2 install. This forces Icinga master and the nodes to be in the same VPC/region.  This will not be the case in our deployment.

**Comment by YarNhoj** [comment]
I'm thinking we need to add another environment variable for the master endpoint.

**Comment by dsuth1** [comment]
I'll create a different var to reference the name of the master cert.  However, this system is built for our icinga master image which will inevitably have the master cert set to the internal fqdn

**Comment by dsuth1** [comment]
Rethinking this, this doesn't loggically make sense.  If you changed the master server to have a cert based off the public facing ip, then you would use that domain-name as the fqdn variable.  Literally, the fqdn used for the filename of the cert has to be the same as the fqdn used for the IP address the client will connect through.  If you need further explanation or clarification, please contact John or myself via email.
